# Bilingual subtitle groups: (first SRT cue, last SRT cue, 中文, English). Timing comes from the SRT; text is lightly cleaned.
G = [
 (1, 2, "视频内容创作，真的进入下一个阶段了", "Video creation has truly entered its next stage"),
 (3, 3, "别再死磕手动剪辑了", "Stop grinding through manual editing"),
 (4, 5, "我先直接给你上实测", "Let me show you a real test first"),
 (6, 7, "看完你就知道，现在 AI 剪辑有多离谱", "You'll see how insane AI editing has become"),
 (8, 9, "现在展示的，就是我用 AI 剪辑的成品", "These are my finished edits, all made by AI"),
 (10, 11, "有 ChatGPT 剪的，有 Claude 剪的", "Some edited by ChatGPT, some by Claude"),
 (12, 14, "ChatGPT 的 5.6、6、Pro、Ultra", "ChatGPT 5.6, 6, Pro, Ultra"),
 (15, 16, "所有的我全部试了，总的来说还可以", "I tried them all — decent overall"),
 (17, 17, "如果把推理程度拉到最高", "If you max out the reasoning effort"),
 (18, 19, "但 Token 成本消耗非常高", "the token cost gets really high"),
 (20, 21, "而 Claude Opus 5.5，简直就是", "But Claude Opus 5.5 simply"),
 (22, 23, "终结比赛了", "ended the game"),
 (24, 25, "说实话，已经完全不输多年的专业剪辑师", "Honestly, it rivals veteran pro editors"),
 (26, 27, "30 分钟，画面的流畅度、转场细节", "30 minutes — smooth visuals, detailed transitions"),
 (28, 29, "甚至对我文案情绪逻辑的理解，都精准得离谱", "It even nails the emotion and logic of my script"),
 (30, 31, "感兴趣的可以翻一下我上一条作品", "Check out my previous video if you're curious"),
 (32, 34, "而且不止口播，这几天我把全品类测了个遍", "Not just talking heads — I tested every category"),
 (35, 36, "知识讲解、趣味解说、剧情短片，甚至音乐 MV", "Explainers, commentary, short films, even music videos"),
 (37, 38, "全能靠 AI 共创出高质量的成片", "All co-created with AI at high quality"),
 (39, 39, "不是那种套模板的流水线", "Not template-driven assembly lines"),
 (40, 41, "而是真的有镜头语言、有叙事节奏的完整作品", "Complete works with real film language and narrative rhythm"),
 (42, 44, "这对我来说，不仅是震撼，也是打击", "For me, it's not just shocking — it's a blow"),
 (45, 46, "我自己就是做 AI 产品的开发者", "I'm an AI product developer myself"),
 (47, 48, "从今年年初一直在死磕 AI 自动剪辑工具", "Since early this year I've been building an AI auto-editing tool"),
 (49, 51, "因为我自己是博主，剪辑真的太费时间了", "As a creator, editing just takes way too much time"),
 (52, 53, "结果 Claude 这波版本更新", "Then this Claude update"),
 (54, 55, "直接把整个赛道的格局都改写了", "rewrote the whole landscape"),
 (56, 57, "而且按现在大模型的迭代速度", "And at today's pace of model iteration"),
 (58, 59, "ChatGPT 和国内的大模型，我相信也会很快跟上", "ChatGPT and Chinese models will catch up soon"),
 (60, 61, "AI + 内容创作，真正驶入了快车道", "AI + content creation is in the fast lane"),
 (62, 63, "所以我第一时间启动了我的 AI 账号", "So I launched my AI account right away"),
 (64, 66, "放在以前，做一条视频从写稿、拍摄到剪辑，少说一两天", "Before, a video took at least a day or two — writing, shooting, editing"),
 (67, 68, "我现在定的目标，是在 AI 开发工作之余", "Now my goal: alongside my AI dev work"),
 (69, 71, "每天花一个小时，分享前沿 AI 技术和工作日常", "spend one hour a day sharing frontier AI and my daily work"),
 (73, 75, "最后掏心窝子说一句：内容创作的新时代真的来了", "From the heart: a new era of content creation is here"),
 (76, 77, "别等你的对手都用 AI 把产能翻了 10 倍甚至更多", "Don't wait until rivals use AI to 10x their output"),
 (78, 78, "你还在一帧一帧地磕剪辑", "while you're still editing frame by frame"),
 (79, 79, "赶紧和 AI 一起行动起来吧", "Get moving with AI now"),
 (80, 81, "有问题可以给我留言，我会尽量解答，拜拜", "Leave me questions, I'll do my best to answer. Bye!"),
]
